---
- name: 'Get config using collections'
  hosts: junos
  serial: 1
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Retrieve the committed configuration
      config:
        retrieve: 'committed'
        format: 'set'
        dest_dir: "{{ playbook_dir }}/roles/junos_config/files/configs/set"
      register: response

    - name: Print the lines in the config.
      debug:
        var: response.config_lines
